# fly.toml app configuration file generated for exchange-server on 2023-10-23T22:15:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "exchange-server"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
